### ISSUE TITLE
Using Apache isn't that hard. :-)

### ISSUE THREAD

**Issue by GrahamDumpleton** [tomokinakamaru/wsgidriver#1]
Didn't know how else to contact you, so ….

> This liberates you from painful operations like:
>
> * manually restarting server each time you edit source codes.
> * configure apache just for debugging

Have you ever tried mod_wsgi-express?

Automatic code reloading:

```
mod_wsgi-express start-server --reload-on-changes --callable-object=app application.py
```

Running pdb debugger on exceptions:

```
mod_wsgi-express start-server --debug-mode --enable-debugger --callable-object=app application.py
```

For installation see:

* https://pypi.python.org/pypi/mod_wsgi

You don't need to do any Apache configuration at all as it is all done for you.

**Comment by tomokinakamaru** [comment]
Thank you for letting me know!
I've never tried it, and actually didn't know it... i think i will use mod_wsgi-express for the future :).

I intended to make a small independent library that acts like 'run' function in flask or bottle. However mod_wsgi-express is more highly-functional.

Now this lib is useless, but I keep this repository because this is my first try to make public lib lol. Anyway I will re-write README.md soon!!

I really appreciate your issue posting, thank you.
